Repository milieuinfo/webcomponent-vl-ui-textarea, pull requests merged in 2019-09, with the labels that each got.

#18 UIG-218
  vl-textarea.src.js
Labels: maintenance

#19 Update link naar demo
  vl-textarea.src.js
Labels: maintenance

#20 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#9 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#22 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#21 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#23 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#24 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#28 UIG-143 - Update bamboo template
  CODEOWNERS
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#29 Update vl-ui-util
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance
