Repository milieuinfo/webcomponent-vl-ui-textarea, pull requests merged in 2020-08, with the labels that each got.

#71 Upgrade huisstijl versie 3.11.5
  demo/vl-textarea.html
  package-lock.json
  package.json
  src/style.css
  src/vl-textarea.js
  src/vl-tinymce-link-toolbar.js
  test/unit/vl-textarea.test.html
Labels: chore

#72 Update dependency tinymce to v5.4.2
  package.json
Labels: chore, dependencies, renovate

#66 Introductie vl-ui-form
  package-lock.json
  package.json
  src/vl-tinymce-link-toolbar.js
Labels: chore

#73 Copy paste van tekst met opmaak zal de opmaak behouden
  dist/vl-textarea.js
  dist/vl-textarea.min.js
  dist/vl-textarea.src.js
  src/vl-textarea.js
  test/e2e/textarea.test.js
Labels: bug
